## May need this in future if content is not in the default location.
#
#content_group:
#    home:
#    pages:
pages:
    default:
        layouts: default
        partials: default
        vars: default
        content: default
        navlinks: default
    /:
        inherit: default
        layouts: /
        content: /
    /about:
        inherit: default
        layouts: /about
        content: /about
    /contact:
        inherit: default
        content: /contact
    /products:
        inherit: default
        layouts: /products
        vars: /products
        content: /products
    /testpage:
        inherit: default
        layouts: /testpage
        content: /testpage
layouts:
    base:
        inherit:
        doc:
            doctype:
            html:
        html:
            head:
            body:
        head:
            charset:
            title:
            author:
            robots:
            stylesheet:
            html5shiv:
        body:
            header:
            navbar:
            main:
            footer:
        header:
        navbar:
            navs:
            navs2: navs
        navs:
            'Home': navlink
            'About Us': navlink
            'Contact Us': navlink
            'Products': navlink
            'Test Page': navlink
        navs2:
            'Login': navlink
            'Sign Up': navlink
        main:
            article:
    default:
        inherit: base
    headlines:
        inherit: default
        main:
            headlines:
            article:
    '/':
        inherit: default
        main:
            headlines:
            cards:
            article:
    /about:
        inherit: default
    /products:
        inherit: default
        main:
            headlines:
            article:
    /testpage:
        inherit: default
        header:
        navbar:
        main:
            headlines:
            cards:
            article:
        footer:
partials:
    base:
        doctype: '<!DOCTYPE {partial}>'
        html: '<html lang="{{lang}}">{partial}</html>'
        head: '<head>{partial}</head>'
        charset: '<meta charset="{partial}"/>'
        title: '<title>{{info.url}} | {{title}}</title>'
        author: '<meta content="{partial}" name="author"/>'
        robots: '<meta content="{partial}" name="robots"/>'
        stylesheet: '<link href="{partial}" rel="stylesheet"/>'
        html5shiv: ''
        body: '<body>{partial}</body>'
        header: '<div class="{partialname}">{partial}</div>'
        navbar: '<div class="{partialname}">{partial}</div>'
        navs: '<ul class="{partialname}">{partial}</ul>'
        navlink: '<li><a href="{partial}">{partialname}</a></li>'
        activenavlink: '<li class="active"><a href="{partial}">{partialname}</a></li>'
        main: '<div class="{partialname}">{partial}</div>'
        footer: '<div class="{partialname}">{partial}</div>'
        headlines: '<div class="{partialname}">{partial}</div>'
        article: '<div class="{partialname}">{partial}</div>'
        cards: '<div class="{partialname}">{partial}</div>'
    html4:
        inherit: base
    html5:
        inherit: base
        html5shiv: '<!--[if ls IE 9] <script src="{partial}"></script><![endif]-->'
        header: '<header>{partial}</header>'
        navbar: '<nav>{partial}</nav>'
        main: '<main>{partial}</main>'
        footer: '<footer>{partial}</footer>'
        article: '<article>{partial}</article>'
    default:
        inherit: html5
vars:
    base:
        lang: 'en'
        charset: 'utf-8'
        author: 'jmdwebsites'
        robots: 'noindex'
        stylesheet: '/page.css'
        title: 'My Web Site'
    html4:
        inherit: base
        doctype: 'HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"'
    html5:
        inherit: base
        doctype: 'html'
        html5shiv: 'https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js'
    default:
        inherit: html5
    /products:
        inherit: default
content:
    base:
        header: '<hr>HEADER: Page URL = {info.url} <br><br><hr>'
        article: '<hr>Default article text ...'
        #footer: '<p><em>&copy jmdwebsites</em></p>' #Need to sort out unicode!
        footer: '<p><em>COPYRIGHT jmdwebsites</em></p>'
    default:
        inherit: base
    /:
        inherit: default
        headlines: ''
        cards: ''
        article: ''
    /about:
        inherit: default
    /contact:
        inherit: default
    /products:
        inherit: default
        headlines: ''
    /testpage:
        header: '<hr>HEADER: Page URL = {info.url} <br><br><hr>'
        navbar: '<hr>NAVBAR: <br><br><hr>'
        headlines: '<hr>HEADLINES: <br><br><hr>'
        cards: '<hr>CARDS: <br><br><hr>'
        article: '<hr>ARTICLE: <br><br><hr>'
        footer: '<hr>FOOTER: <br><br><hr>'
navlinks:
    default:
        'Home': '/'
        'About Us': '/about'
        'Contact Us': '/contact'
        'Products': '/products'
        'Test Page': '/testpage'
        'Login': '#'
        'Sign Up': '#'
