## May need this in future if content is not in the default location.
#content_group:
#    home:
#    pages:
theme:
    name: products
pages:
    default:
        layouts: default
        partials: default
        vars: default
        content: default
        navlinks: default
    page:
        layouts: page
        partials: base
        vars: page
        content: page
        navlinks: page
        data: base
    /:
        inherit: page
        layouts: home_page
        content: home_page
        vars:    /
    /testpage:
        inherit: page
        layouts: test_page
        content: test_page
        vars:    /testpage
    /about:
        inherit: page
        vars:    /about
    /contact:
        inherit: page
        vars:    /contact
    /products:
        inherit: page
        layouts: products_page
        content: products_page
        vars:    /products
layouts:
    base:
        inherit:
        doc:
            doctype:
            html:
        html:
            head:
            body:
        head:
            charset:
            title:
            author:
            robots:
            stylesheet:
            html5shiv:
        body:
            header:
            navbar:
            main:
            footer:
        header:
        navbar:
            navs:
            navs2: navs
        navs:
            'Home': navlink
            'About Us': navlink
            'Contact Us': navlink
            'Products': navlink
            'Test Page': navlink
        navs2:
            'Login': navlink
            'Sign Up': navlink
        main:
            article:
    default:
        inherit: base
    page:
        inherit: default
    home_page:
        inherit: page
        main:
            headlines:
            cards:
            article:
    headlines_page:
        inherit: page
        main:
            headlines:
            article:
    products_page:
        inherit: headlines_page
    test_page:
        inherit: default
        header:
        navbar:
        main:
            headlines:
            cards:
            article:
        footer:
navlinks:
    default:
        'Home': '/'
        'About Us': '/about'
        'Contact Us': '/contact'
        'Products': '/products'
        'Test Page': '/testpage'
        'Login': '#'
        'Sign Up': '#'
    page:
        inherit: default
data:
    base:
        phone: '111'
