## May need this in future if content is not in the default location.
#content_group:
#    home:
#    pages:
theme:
    name: products
pages:
    page:
        layouts: page
        partials: base
        vars: page
        content: page
        navlinks: page
        descriptions: page
        data: page
        object: page
    /:
        inherit: page
        layouts: home_page
        content: home_page
        vars:    page
    /testpage:
        inherit: page
        layouts: test_page
        content: test_page
        vars:    page
    /about:
        inherit: page
        content: about_page
        vars:    page
    /contact:
        inherit: page
        content: contact_page
        vars:    page
    /products:
        inherit: page
        layouts: products_page
        content: products_page
        vars:    page
layouts:
    page:
        inherit:
        doc:
            doctype:
            html:
        html:
            head:
            body:
        head:
            charset:
            title:
            author:
            robots:
            stylesheet:
            html5shiv:
        body:
            header:
            navbar:
            main:
            footer:
        header:
        navbar:
            navs:
            navs2: navs
        navs:
            nav_home: navlink
            nav_about: navlink
            nav_contact: navlink
            nav_products: navlink
            nav_testpage: navlink
        navs2:
            nav_login: navlink
            nav_signup: navlink
        main:
            article:
    home_page:
        inherit: page
        main:
            headlines:
            cards:
            article:
    headlines_page:
        inherit: page
        main:
            headlines:
            article:
    products_page:
        inherit: headlines_page
    test_page:
        inherit: page
        header:
        navbar:
        main:
            headlines:
            cards:
            article:
        footer:
navlinks:
    page:
        nav_home: '/'
        nav_about: '/about'
        nav_contact: '/contact'
        nav_products: '/products'
        nav_testpage: '/testpage'
        nav_login: '#'
        nav_signup: '#'
object:
    page:
        stats: 'Stats=78%'