content_group:
    home:
    pages:
pages:
    default:
        layouts: default
        partials: default
        vars: default
        content: default
        #navbar: default
        navlinks: default
    about:
        inherit: default
        layouts: about
    products:
        inherit: default
        layouts: products
        vars: products
        content: products
layouts:
    base:
        inherit:
        doc:
            doctype:
            html:
        html:
            head:
            body:
        head:
            charset:
        body:
            header:
            navbar:
            main:
            footer:
        header:
        navbar:
            navs:
            navs2: navs
        navs:
            'Home': navlink
            'About Us': navlink
            'Contact Us': navlink
            'Products': navlink
        navs2:
            'Login': navlink
            'Sign Up': navlink
        main:
            article:
    default:
        inherit: base
    headlines:
        inherit: default
        main:
            headlines:
            article:
    products:
        inherit: default
        head:
            charset:
            title:
            author:
            robots:
            stylesheet:
            html5shiv:
    about:
        inherit: default
        main:
            cards:
            article:
partials:
    base:
        doctype: '<!DOCTYPE {doctype}>'
        html: '<html lang="{{lang}}">{html}</html>'
        head: '<head>{head}</head>'
        charset: '<meta charset="{charset}"/>'
        title: <title>{{title}}</title>
        author: '<meta content="{author}" name="author"/>'
        robots: '<meta content="{robots}" name="robots"/>'
        stylesheet: '<link href="{stylesheet}" rel="stylesheet"/>'
        html5shiv: ''
        body: '<body>{body}</body>'
        header: '<div class="header">{header}</div>'
        navbar: '<div class="navbar">{navbar}</div>'
        #navs: '<ul class="navs">{navs}</ul>'
        navs: '<ul class="{partialname}">{partial}</ul>'
        #navlink: '<li><a href="{{{navlink}}}">{navlink}</a></li>'
        navlink: '<li><a href="{partial}">{partialname}</a></li>'
        main: '<div class="main">{main}</div>'
        footer: '<div class="footer">{footer}</div>'
        headlines: '<div class="headlines">{headlines}</div>'
        article: '<div class="article">{article}</div>'
        cards: '<div class="cards">{cards}</div>'
    html4:
        inherit: base
    html5:
        inherit: base
        html5shiv: '<!--[if ls IE 9] <script src="{html5shiv}"></script><![endif]-->'
        header: '<header>{header}</header>'
        navbar: '<nav>{navbar}</nav>'
        main: '<main>{main}</main>'
        footer: '<footer>{footer}</footer>'
        article: '<article>{article}</article>'
    default:
        inherit: base
vars:
    base:
        lang: 'en'
        charset: 'utf-8'
        author: 'jmdwebsites'
        robots: 'noindex'
        stylesheet: '/page.css'
        title: 'My Web Page'
    html4:
        inherit: base
        doctype: 'HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"'
    html5:
        inherit: base
        doctype: 'html'
        html5shiv: 'https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js'
    default:
        inherit: html5
    products:
        inherit: default
content:
    default:
        header: ''
        navs: ''
        navs2: ''
        article: ''
        #footer: '<p><em>&copy jmdwebsites</em></p>' #Need to sort out unicode!
        footer: '<p><em>COPYRIGHT jmdwebsites</em></p>'
        headlines: ''
        cards: ''
    products:
        inherit: default
        article: 'Default article text ...'
navlinks:
    default:
        'Home': '/'
        'About Us': '/about'
        'Contact Us': '/contact'
        'Products': '/products'
        'Login': '#'
        'Sign Up': '#'
