pages:
    default:
        layouts: default
        partials: default
        vars: default
        content: default
    about:
        inherit: default
        layouts: about
    products:
        inherit: default
        layouts: products
        vars: products
        content: products
layouts:
    base:
        inherit:
        doc:
            doctype:
            html:
        html:
            head:
            body:
        head:
            charset:
        body:
            header:
            main:
            footer:
        header:
        main:
            article:
    default:
        inherit: base
    headlines:
        inherit: default
        main:
            headlines:
            article:
    products:
        inherit: headlines
        head:
            charset:
            title:
            author:
            robots:
            stylesheet:
            html5shiv:
    about:
        inherit: default
        main:
            cards:
            article:
partials:
    base:
        doctype: '<!DOCTYPE {doctype}>'
        html: '<html lang="{{lang}}">{html}</html>'
        head: '<head>{head}</head>'
        charset: '<meta charset="{charset}"/>'
        title: <title>{{title}}</title>
        author: '<meta content="{author}" name="author"/>'
        robots: '<meta content="{robots}" name="robots"/>'
        stylesheet: '<link href="{stylesheet}" rel="stylesheet"/>'
        html5shiv: ''
        body: '<body>{body}</body>'
        header: '<div class="header">{header}</div>'
        main: '<div class="main">{main}</div>'
        footer: '<div class="footer">{footer}</div>'
        headlines: '<div class="headlines">{headlines}</div>'
        article: '<div class="article">{article}</div>'
        cards: '<div class="cards">{cards}</div>'
    html4:
        inherit: base
    html5:
        inherit: base
        html5shiv: '<!--[if ls IE 9] <script src="{html5shiv}"></script><![endif]-->'
        header: '<header>{header}</header>'
        main: '<main>{main}</main>'
        footer: '<footer>{footer}</footer>'
        article: '<article>{article}</article>'
    default:
        inherit: base
vars:
    base:
        lang: 'en'
        charset: 'utf-8'
        author: 'jmdwebsites'
        robots: 'noindex'
        stylesheet: '/page.css'
        title: 'My Web Page'
    html4:
        inherit: base
        doctype: 'HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"'
    html5:
        inherit: base
        doctype: 'html'
        html5shiv: 'https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js'
    default:
        inherit: html5
    products:
        inherit: default
content:
    default:
        header: ''
        article: ''
        footer: ''
        headlines: ''
        cards: ''
    products:
        inherit: default
        article: 'Default article text ...'
        footer: 'Products footer!'
